Repository ovh-ux/ng-ovh-cloud-universe-components, pull requests merged in 2019-02, with the labels that each got.

#3 Feat/cloud common
  package.json
  src/index.js
  src/message/index.js
  src/message/service.js
  src/navigation/index.js
  src/navigation/service.js
  src/poll/index.js
  src/poll/ovh/service.js
  src/poll/service.js
  yarn.lock
Labels: enhancement

#4 feat(cui-message): add cuiMessage component
  package.json
  src/cui/index.js
  src/cui/message/component.js
  src/cui/message/controller.js
  src/cui/message/index.js
  src/cui/message/template.html
  src/cui/message/unique-message-composite.js
  src/cui/tabs/index.js
  yarn.lock
Labels: enhancement

#6 fix(cui-message): update cuiMessageContainer component name
  src/cui/message/index.js
Labels: bug

#5 Feat/cui dropdown-menu/guide/page
  .htmlhintrc
  package.json
  src/cui/dropdown-menu/component.js
  src/cui/dropdown-menu/controller.js
  src/cui/dropdown-menu/index.js
  src/cui/dropdown-menu/index.less
  src/cui/dropdown-menu/template.html
  src/cui/guide-component/component.js
  src/cui/guide-component/controller.js
  src/cui/guide-component/index.js
  src/cui/guide-component/index.less
  src/cui/guide-component/template.html
  src/cui/index.js
  src/cui/page/content/component.js
  src/cui/page/content/template.html
  src/cui/page/header/component.js
  src/cui/page/header/template.html
  src/cui/page/header/title/component.js
  src/cui/page/header/title/template.html
  src/cui/page/index.js
  src/cui/page/index.less
  yarn.lock
Labels: enhancement

#10 feat(directives): add directives
  src/autofocus/directive.js
  src/autofocus/index.js
  src/autoselect/directive.js
  src/autoselect/index.js
  src/clickEnterOnKeypress/directive.js
  src/clickEnterOnKeypress/index.js
  src/index.js
  src/smoothScrollHere/directive.js
  src/smoothScrollHere/index.js
Labels: feature, quality check ok

#12 fix(peerdeps): upgrade ovh-api-services to v4.0.0
  package.json
  yarn.lock
Labels: bug

#8 feat(ordered-hash): add ordered-hash factory
  src/index.js
  src/orderedHash/factory.js
  src/orderedHash/index.js
Labels: feature, quality check ok

#9 feat(vrack): add vrack service
  src/index.js
  src/vrack/constants.js
  src/vrack/index.js
  src/vrack/select/controller.js
  src/vrack/select/template.html
  src/vrack/service.js
  src/vrack/translations/Messages_fr_FR.json
Labels: feature, quality check ok, translation required

#7 feat(helper): add helper and cui-modal component
  package.json
  src/config/index.js
  src/config/provider.js
  src/cui/index.js
  src/cui/modal/body/component.js
  src/cui/modal/body/template.html
  src/cui/modal/component.js
  src/cui/modal/footer/component.js
  src/cui/modal/footer/template.html
  src/cui/modal/header/component.js
  src/cui/modal/header/template.html
  src/cui/modal/index.js
  src/cui/modal/index.less
  src/cui/modal/template.html
  src/cui/modal/text/component.js
  src/cui/modal/text/template.html
  src/featureAvailability/constants.js
  src/featureAvailability/index.js
  src/featureAvailability/service.js
  src/helper/controller/modal/confirmation/controller.js
  src/helper/controller/modal/confirmation/template.html
  src/helper/controller/modal/info/controller.js
  src/helper/controller/modal/info/template.html
  src/helper/controller/modal/name-change/controller.js
  src/helper/controller/modal/name-change/template.html
  src/helper/controller/modal/service.js
  src/helper/controller/modal/warning/controller.js
  src/helper/controller/modal/warning/template.html
  src/helper/controller/navigation/service.js
  src/helper/controller/request/service.js
  src/helper/controller/service.js
  src/helper/index.js
  src/helper/order/service.js
  src/helper/service/service.js
  src/helper/translations/Messages_fr_FR.json
  src/helper/url/service.js
  src/index.js
  src/vrack/constants.js
  src/vrack/index.js
  src/vrack/select/controller.js
  src/vrack/select/template.html
  src/vrack/service.js
  src/vrack/translations/Messages_fr_FR.json
  yarn.lock
Labels: feature, quality check ok, translation required
